apiVersion: v1
kind: Service
metadata:
  name: eks-example
  namespace: eks-example
  labels:
    app: eks-example
spec:
  type: LoadBalancer
  selector:
    app: eks-example
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: http